"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.contrib import staticfiles

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nr*5^pmjmi6&lbq*ssxs64icl5wfm*q4m-=r9b+$zg5h1=1q5w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'knox',
    'corsheaders',
    'drf_yasg',
    'content',
    'booking',
    'colorfield',
    'menu',
    'ckeditor'
]
CHOICES = (
    ('Week Days', 'Week Days'),
    ('Week end', 'Week end'),
)

BOOKING_STATUS = (
    ('Confirmed', 'Confirmed'),
    ('Cancelled', 'Cancelled'),
    ('EventPassed', 'EventPassed'),
    ('Pending', 'Pending'),
)

AvailableSlots = (
    ("11:00 AM", "11:00 AM"),
    ("11:15 AM", "11:15 AM"),
    ("11:30 AM", "11:30 AM"),
    ("11:45 AM", "11:45 AM"),
    ("12:00 PM", "12:00 PM"),
    ("12:15 PM", "12:15 PM"),
    ("12:30 PM", "12:30 PM"),
    ("12:45 PM", "12:45 PM"),
    ("01:00 PM", "01:00 PM"),
    ("01:15 PM", "01:15 PM"),
    ("01:30 PM", "01:30 PM"),
    ("01:45 PM", "01:45 PM"),
    ("02:00 PM", "02:00 PM"),
    ("02:15 PM", "02:15 PM"),
    ("02:30 PM", "02:30 PM"),
    ("02:45 PM", "02:45 PM"),
    ("03:00 PM", "03:00 PM"),
    ("03:15 PM", "03:15 PM"),
    ("03:30 PM", "03:30 PM"),
    ("03:45 PM", "03:45 PM"),
    ("04:00 PM", "04:00 PM"),
    ("04:15 PM", "04:15 PM"),
    ("04:30 PM", "04:30 PM"),
    ("04:45 PM", "04:45 PM"),
    ("05:00 PM", "05:00 PM"),
    ("05:15 PM", "05:15 PM"),
    ("05:30 PM", "05:30 PM"),
    ("05:45 PM", "05:45 PM"),
    ("06:00 PM", "06:00 PM"),
    ("06:15 PM", "06:15 PM"),
    ("06:30 PM", "06:30 PM"),
    ("06:45 PM", "06:45 PM"),
    ("07:00 PM", "07:00 PM"),
    ("07:15 PM", "07:15 PM"),
    ("07:30 PM", "07:30 PM"),
    ("07:45 PM", "07:45 PM"),
    ("08:00 PM", "08:00 PM"),
    ("08:15 PM", "08:15 PM"),
    ("08:30 PM", "08:30 PM"),
    ("08:45 PM", "08:45 PM"),
    ("09:00 PM", "09:00 PM"),
    ("09:15 PM", "09:15 PM"),
    ("09:30 PM", "09:30 PM"),
    ("09:45 PM", "09:45 PM"),
    ("10:00 PM", "10:00 PM"),
    ("10:15 PM", "10:15 PM"),
    ("10:30 PM", "10:30 PM"),
    ("10:45 PM", "10:45 PM"),
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# TESTING EMAIL:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'Monitor.io.app@gmail.com'
# EMAIL_HOST_PASSWORD = '^m\$9E@4X7#Ww.:C'


EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'AltETWeb@outlook.com'
EMAIL_HOST_PASSWORD = 'gg1*NG0v5kF2'

# gg1*NG0v5kF2
# AltETWeb@outlook.com

# Server name: outlook.office365.com
# Port: 995
# Encryption method: TLS
# Server name: outlook.office365.com
# Port: 993
# Encryption method: TLS
# Server name: smtp.office365.com
# Port: 587
# Encryption method: STARTTLS
