# Generated by Django 4.1 on 2022-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booktablecover'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTableCover2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_Img', models.ImageField(upload_to='BookingTable/')),
            ],
            options={
                'verbose_name_plural': 'Book Table Cover 2',
            },
        ),
    ]
