# Generated by Django 4.1 on 2022-08-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booktablecover2'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktablecover2',
            name='Text',
            field=models.TextField(default=' please '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booktablecover2',
            name='cover_Img',
            field=models.ImageField(help_text='recommended dimensions 1000x403', upload_to='BookingTable/'),
        ),
    ]
