# Generated by Django 4.1 on 2022-08-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_tablebooking_status_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablebooking',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='BookingID',
            field=models.CharField(blank=True, default='migTJ6GN2zTP', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='Status_booking',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('EventPassed', 'EventPassed'), ('Pending', 'Pending')], default='Confirmed', max_length=100, null=True),
        ),
    ]
