# Generated by Django 4.1 on 2022-08-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_tablebooking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='BookingID',
            field=models.CharField(blank=True, default='WAFGF4BF7ayb', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='Get_Emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='Type_of_Booking',
            field=models.BooleanField(default=False),
        ),
    ]
