# Generated by Django 4.1 on 2022-08-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_tablebooking_bookingid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='BookingID',
            field=models.CharField(blank=True, default='Dr6T1sV76X2I', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='Email',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='First_Name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='Last_Name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='Telephone_Number',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
    ]
