# Generated by Django 4.1 on 2022-08-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_tablebooking_bookingid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='BookingID',
            field=models.CharField(blank=True, default='ewlkQ8kArZOz', max_length=12, null=True),
        ),
    ]
