# Generated by Django 4.1 on 2022-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_tablebooking_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='BookingID',
            field=models.CharField(blank=True, default='Y5icuneTX3M3UM6L', max_length=16, null=True, unique=True),
        ),
    ]
