# Generated by Django 4.1 on 2022-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_tablebooking_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='BookingID',
            field=models.CharField(blank=True, default='2FDE3CAC70B34AED', max_length=16, null=True, unique=True),
        ),
    ]
