# Generated by Django 4.1 on 2022-08-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_tablebooking_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='BookingID',
            field=models.CharField(blank=True, default='6A8B15C53D43428E', max_length=16, null=True, unique=True),
        ),
    ]
