# Generated by Django 4.1 on 2022-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='MenuCarousel/')),
                ('Heading', models.CharField(max_length=100)),
                ('Para', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Menu Carousel',
            },
        ),
        migrations.CreateModel(
            name='MenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Type', models.CharField(choices=[('Week Days', 'Week Days'), ('Week end', 'Week end')], max_length=300, unique=True)),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Menu Day',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Menu_File', models.FileField(blank=True, null=True, upload_to='MenuFile/')),
                ('Days', models.ManyToManyField(to='menu.menuday')),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
