# Generated by Django 4.1 on 2022-08-10 19:31

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucarousel',
            old_name='Heading',
            new_name='Caption_Heading',
        ),
        migrations.RenameField(
            model_name='menucarousel',
            old_name='Para',
            new_name='Caption_subHeading',
        ),
        migrations.AddField(
            model_name='menucarousel',
            name='Color_Caption_Heading',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='menucarousel',
            name='Color_Caption_subHeading',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='menucarousel',
            name='ImageOpacity',
            field=models.IntegerField(blank=True, help_text='Enter in Percentage', null=True),
        ),
        migrations.AlterField(
            model_name='menucarousel',
            name='Image',
            field=models.ImageField(help_text='Recommended Dimensions 2000x650', upload_to='MenuCarousel/'),
        ),
    ]
