# Generated by Django 4.1 on 2022-08-11 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_heading_menucarousel_caption_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Days',
        ),
        migrations.AddField(
            model_name='menu',
            name='WeekDay',
            field=models.BooleanField(blank=True, default=False, help_text='Enable it to display', null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='WeekDayEndTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='WeekDayStartTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='WeekEnd',
            field=models.BooleanField(blank=True, default=False, help_text='Enable it to display', null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='WeekEndEndTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='WeekEndStartTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
