# Generated by Django 4.1 on 2022-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'SocialMedia',
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weekdays', models.CharField(blank=True, max_length=100, null=True)),
                ('Weekdays_Start_Time', models.DateTimeField(blank=True, null=True)),
                ('Weekdays_End_Time', models.DateTimeField(blank=True, null=True)),
                ('WeekEndTime', models.CharField(blank=True, max_length=100, null=True)),
                ('WeekEndTime_Start_Time', models.DateTimeField(blank=True, null=True)),
                ('WeekEndTime_End_Time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Timing',
            },
        ),
    ]
