# Generated by Django 4.1 on 2022-08-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_weekdays_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekdays',
            options={},
        ),
    ]
