# Generated by Django 4.1 on 2022-08-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_weekdays_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
            ],
        ),
    ]
