# Generated by Django 4.1 on 2022-08-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_time_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Type', models.CharField(choices=[('WeekDays', 'WeekDays'), ('Weekend', 'Weekend')], max_length=300)),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Menu_Day',
            },
        ),
        migrations.DeleteModel(
            name='Time_day',
        ),
        migrations.DeleteModel(
            name='Weekdays',
        ),
        migrations.AlterField(
            model_name='menu',
            name='Days',
            field=models.ManyToManyField(to='content.menu_day'),
        ),
    ]
