# Generated by Django 4.1 on 2022-08-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_menuday_day_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuday',
            name='Day_Type',
            field=models.CharField(choices=[('Week Days', 'Week Days'), ('Week end', 'Week end')], max_length=300, unique=True),
        ),
    ]
