# Generated by Django 4.1 on 2022-08-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_menuday_day_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='MenuFile',
            new_name='Menu_File',
        ),
    ]
