# Generated by Django 4.1 on 2022-08-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_menufile_menu_menu_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingID', models.CharField(blank=True, max_length=100, null=True)),
                ('Booking_Time', models.TimeField()),
                ('Booking_Date', models.DateField()),
                ('Party_Size', models.IntegerField()),
                ('FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('TelephoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('TypeofBooking', models.BooleanField()),
                ('GetEmails', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
