# Generated by Django 4.1 on 2022-08-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_tablebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablebooking',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='tablebooking',
            old_name='GetEmails',
            new_name='Get_Emails',
        ),
        migrations.RenameField(
            model_name='tablebooking',
            old_name='TelephoneNumber',
            new_name='Telephone_Number',
        ),
        migrations.RenameField(
            model_name='tablebooking',
            old_name='TypeofBooking',
            new_name='Type_of_Booking',
        ),
    ]
