# Generated by Django 4.1 on 2022-08-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_rename_firstname_tablebooking_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablebooking',
            old_name='LastName',
            new_name='Last_Name',
        ),
    ]
