# Generated by Django 4.1 on 2022-08-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_instagrampost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(upload_to='BrandLogo/')),
            ],
            options={
                'verbose_name_plural': 'Brand Logo',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('GoogleMaps', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
