# Generated by Django 4.1 on 2022-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_brandlogo_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='Post_Image',
            field=models.ImageField(blank=True, help_text='Recommended Dimensions 500x500', null=True, upload_to='Instagram'),
        ),
    ]
