# Generated by Django 4.1 on 2022-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_instagrampost_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='URL',
            field=models.URLField(blank=True, help_text='Paste IG Link e.g https://www.instagram.com/', null=True),
        ),
    ]
