# Generated by Django 4.1 on 2022-08-08 10:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_instagrampost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
