# Generated by Django 4.1 on 2022-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_rename_color_carousel_color_caption_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='ImageOpacity',
            field=models.IntegerField(blank=True, help_text='Enter in Percentage', null=True),
        ),
    ]
