# Generated by Django 4.1 on 2022-08-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_remove_timing_weekendtime_remove_timing_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='WeekEndTime_End_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='WeekEndTime_Start_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='Weekdays_End_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='Weekdays_Start_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
