# Generated by Django 4.1 on 2022-08-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_alter_timing_weekendtime_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paragraph', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'AboutUs',
            },
        ),
    ]
