# Generated by Django 4.1 on 2022-08-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_homeimage_alter_aboutus_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeImage',
        ),
    ]
