# Generated by Django 4.1 on 2022-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_homepageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Address & Details',
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuDay',
        ),
    ]
